FROM agrigorev/model-2025-hairstyle:v1

# Install requirements
RUN pip install numpy Pillow onnxruntime

# Copy your lambda code
COPY lambda_function.py .

# Set the CMD to your handler
CMD [ "lambda_function.lambda_handler" ]